### ISSUE TITLE
Performance Is 2x Worst For Large Data Structures

### ISSUE THREAD

**Issue by s0kil** [LuKks/like-json#6]
I have created a simple benchmark testing encoding of large data structure.
It turns out `like-json` does not handle it so well.
https://github.com/s0kil/like-json/blob/master/test.html

**Comment by LuKks** [comment]
I don't agree, check this out: https://js.do/code/409727
```
json: 21594.494140625ms (21.5s)
like: 3639.829833984375ms (3.6s)
```
I'm using Linux with Chrome/80.

Note: if you open the link, it will freeze some seconds until benchmark ends then in the console you can see the results.

Really sorry the delay for the response!
